version: "3.8"

services:
  web:
    build: ./infra/images/php
    container_name: web
    volumes:
      - ./app:/var/www/poke
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - backend

  database:
    image: mariadb:10.3
    restart: always
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poke
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - ./infra/data/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend: